// <auto-generated />
using System;
using ISStudyAbroad2023.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISStudyAbroad2023.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20230505132758_sqlite.local_migration_445")]
    partial class sqlitelocal_migration_445
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("ISStudyAbroad2023.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ISStudyAbroad2023.Models.Thought", b =>
                {
                    b.Property<int>("ThoughtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ThoughtDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ThoughtId");

                    b.HasIndex("StudentId");

                    b.ToTable("Thoughts");
                });

            modelBuilder.Entity("ISStudyAbroad2023.Models.Thought", b =>
                {
                    b.HasOne("ISStudyAbroad2023.Models.Student", "Person")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
