// <auto-generated />
using ISStudyAbroad2023.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISStudyAbroad2023.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20230503154810_sqlite.local_migration_605")]
    partial class sqlitelocal_migration_605
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");
#pragma warning restore 612, 618
        }
    }
}
